# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pozdrav.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pozdrav.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpozdrav.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x16\n\x05Point\x12\r\n\x05value\x18\x02 \x01(\x02\"\x1b\n\nPointIndex\x12\r\n\x05index\x18\x01 \x01(\x05\x32\xa3\x01\n\x05Serve\x12#\n\x07SendOne\x12\x0b.grpc.Point\x1a\x0b.grpc.Empty\x12&\n\x08SendMore\x12\x0b.grpc.Point\x1a\x0b.grpc.Empty(\x01\x12\'\n\x06GetOne\x12\x10.grpc.PointIndex\x1a\x0b.grpc.Point\x12$\n\x06GetAll\x12\x0b.grpc.Empty\x1a\x0b.grpc.Point0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pozdrav_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_POINT']._serialized_start=32
  _globals['_POINT']._serialized_end=54
  _globals['_POINTINDEX']._serialized_start=56
  _globals['_POINTINDEX']._serialized_end=83
  _globals['_SERVE']._serialized_start=86
  _globals['_SERVE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
